### ISSUE TITLE
Where can I download the complete raw data of kitti dataset ?

### ISSUE THREAD

**Issue by Oofs** [stevenliu216/568-Final-Project#2]
Hi liu,
  I found that kitti website only give us links of seperated raw dataset in raw data section. And in odometry section, it give raw camera, lidar data but with no timestamps and no gnss data.
  Do you know where can I download the complete raw dataset of KITTI ( like KITTI 08 used in your demo) ?

Sincerely, 
Claude

**Comment by stevenliu216** [comment]
Hello Claude,

The [odometry devkit](https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_odometry.zip) contains a readme.txt file that maps each odometry sequence to its raw data name. 

For example, 
```08: 2011_09_30_drive_0028 001100 005170```

Says that sequence 08 is included in the 2011_09_30_drive_0028 raw dataset file, from timestamps 1100 to 5170. You can use this approach to individually download all 10 sequences which will include more data such as timestamps and 3D GPS/IMU data. 

However, do keep in mind that the KITTI odometry evaluation does not provide GPS/IMU data when evaluating any submissions, which is why it was not provided in the combined data files.

Hope this helps!

**Comment by Oofs** [comment]
Hi liu,
Thanks for your reply. It really helps!
Starting to test loam with closure trajectory data...
Claude
